<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Applicant extends Model
{
    use HasFactory;

    protected $primaryKey = 'applicant_id';
    public $timestamps = false;

    protected $fillable = [
        'personal_title',
        'personal_surname',
        'personal_first_name',
        'personal_sa_citizen',
        'personal_id_number',
        'personal_dob',
        'personal_marital_status',
        'personal_disablity_status',
        'personal_disability_description',
        'personal_gender',
        'personal_room_preference',
        'personal_room_with_fridge',
        'personal_application_year',
        'personal_semester_year',
        'personal_kovacs_arrival_date',
        'personal_home_street_address',
        'personal_home_province',
        'personal_home_postal_code',
        'personal_home_city',
        'personal_home_country',
        'personal_current_street_address',
        'personal_current_province',
        'personal_current_postal_code',
        'personal_current_city',
        'personal_current_country',
        'personal_legal_address_choice',
        'personal_legal_street_address',
        'personal_legal_province',
        'personal_legal_postal_code',
        'personal_legal_city',
        'personal_legal_country',
        'personal_applicant_telephone',
        'personal_applicant_telephone_country_code',
        'personal_applicant_telephone_area_code',
        'personal_applicant_mobile',
        'personal_applicant_mobile_country_code',
        'personal_applicant_mobile_area_code',
        'personal_applicant_fax',
        'personal_applicant_fax_country_code',
        'personal_applicant_fax_area_code',
        'personal_applicant_email',
        'personal_parent_telephone',
        'personal_parent_telephone_country_code',
        'personal_parent_telephone_area_code',
        'personal_parent_mobile',
        'personal_parent_mobile_country_code',
        'personal_parent_mobile_area_code',
        'personal_parent_fax',
        'personal_parent_fax_country_code',
        'personal_parent_fax_area_code',
        'personal_parent_email',
        'personal_kovacs_before',
        'personal_medical_aid',
        'personal_medical_aid_number',
        'personal_medical_aid_name',
        'personal_medical_aid_member_name',
        'personal_medical_aid_member_surname',
        'personal_illness_allergy',
        'personal_kovacs_legal_address_accept',
        'personal_kovacs_legal_address_accept',
        'academic_highest_qualification',
        'academic_uwc_student_number',
        'academic_uwc_study_programme',
        'academic_study_year',
        'academic_remaining_years',
        'academic_pg_start_date',
        'academic_pg_end_date',
        'academic_application_status',
        'academic_uwc_residence_application',
        'academic_study_application_elsewhere',
        'fees_parent_responsible_payment',
        'fees_student_responsible_payment',
        'fees_partly_bursary_responsible_payment',
        'fees_party_responsible_payment',
        'fees_nsfas_bursary',
        'fees_bursary_covers_payment',
        'fees_government_employee_payment',
        'fees_title',
        'fees_surname',
        'fees_first_name',
        'fees_burser_name',
        'fees_telephone',
        'fees_telephone_country_code',
        'fees_telephone_area_code',
        'fees_mobile',
        'fees_mobile_country_code',
        'fees_mobile_area_code',
        'fees_fax',
        'fees_fax_country_code',
        'fees_fax_area_code',
        'fees_email',
        'credit_prepaid_fees',
        'credit_current_residence',
        'credit_current_residence_rental_amount',
        ' credit_current_residence_reference_letter',
        'credit_employed',
        'credit_occupation',
        'credit_mother_occupation',
        'credit_father_occupation',
        'credit_guardian_occupation',
        'credit_company_credit_1',
        'credit_company_credit_1_account',
        'credit_company_credit_2',
        'credit_company_credit_2_account',
        'credit_bank_statement_provided',
        'credit_proof_income_provided',
        'bursary_annual_value',
        'bursary_accommodation_value',
        'bursary_confirm_letter_provided',
        'bursary_approval_status',
        'bursary_residence_payment_date',
        'bursary_residence_fees_recipient',
        'confirm_kovacs_credit_eva',
        'confirm_info_correct',
        'confirm_application_date',
        'confirm_name',
        'confirm_signature',
        'user_id',
        'room_id',
    ];
}
